kernelsu-objs := core/init.o

kernelsu-objs += feature/kernel_umount.o
kernelsu-objs += feature/sulog.o
kernelsu-objs += feature/sucompat.o

kernelsu-objs += hook/lsm_hook.o
kernelsu-objs += hook/setuid_hook.o
kernelsu-objs += hook/syscall_event_bridge.o
kernelsu-objs += hook/syscall_hook_manager.o
kernelsu-objs += hook/tp_marker.o
ifeq ($(CONFIG_ARM64),y)
kernelsu-objs += hook/arm64/patch_memory.o
kernelsu-objs += hook/arm64/syscall_hook.o
else ifeq ($(CONFIG_X86_64),y)
kernelsu-objs += hook/x86_64/patch_memory.o
kernelsu-objs += hook/x86_64/syscall_hook.o
endif

kernelsu-objs += infra/file_wrapper.o
kernelsu-objs += infra/event_queue.o
kernelsu-objs += infra/seccomp_cache.o
kernelsu-objs += infra/su_mount_ns.o
kernelsu-objs += infra/symbol_resolver.o

ifneq ($(CONFIG_KSU_DISABLE_MANAGER),y)
kernelsu-objs += manager/apk_sign.o
kernelsu-objs += manager/pkg_observer.o
kernelsu-objs += manager/throne_tracker.o
endif

kernelsu-objs += policy/allowlist.o
kernelsu-objs += policy/app_profile.o
kernelsu-objs += policy/feature.o

kernelsu-objs += runtime/boot_event.o
kernelsu-objs += runtime/ksud_integration.o

kernelsu-objs += selinux/selinux.o
kernelsu-objs += selinux/rules.o
kernelsu-objs += selinux/sepolicy.o

kernelsu-objs += sulog/event.o
kernelsu-objs += sulog/fd.o

kernelsu-objs += supercall/dispatch.o
kernelsu-objs += supercall/perm.o
kernelsu-objs += supercall/supercall.o

kernelsu-objs += feature/adb_root.o

kernelsu-objs += feature/selinux_hide.o

ifdef KBUILD_EXTMOD
ifeq ($(CONFIG_KSU_DISABLE_MANAGER),y)
ccflags-y += -DCONFIG_KSU_DISABLE_MANAGER=1
endif
ifeq ($(CONFIG_KSU_DISABLE_POLICY),y)
ccflags-y += -DCONFIG_KSU_DISABLE_POLICY=1
endif
ifeq ($(CONFIG_KSU_DEBUG),y)
ccflags-y += -DCONFIG_KSU_DEBUG=1
endif
ifeq ($(CONFIG_KSU_X86_PATCH_SYSCALL_DISPATCHER),y)
ccflags-y += -DCONFIG_KSU_X86_PATCH_SYSCALL_DISPATCHER=1
endif
endif

kernelsu-objs += extras.o

ccflags-y += -I$(srctree)/security/selinux -I$(srctree)/security/selinux/include
ccflags-y += -I$(objtree)/security/selinux -include $(srctree)/include/uapi/asm-generic/errno.h

ifneq ($(KBUILD_EXTMOD),)
# 6.18 exports the external module source as srcroot when M/MO are used.
ifneq ($(srcroot),)
KSU_KERNEL_DIR := $(srcroot)
endif
endif
ifndef KSU_KERNEL_DIR
ifeq ($(filter /%,$(src)),)
KSU_KERNEL_DIR := $(srctree)/$(src)
else
KSU_KERNEL_DIR := $(src)
endif
endif

ccflags-y += -I$(KSU_KERNEL_DIR) -I$(KSU_KERNEL_DIR)/include

obj-$(CONFIG_KSU) += kernelsu.o

MDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

KSU_GIT_VERSION := 2638
KSU_GIT_VERSION_VALID := 1

$(eval KSU_VERSION=$(shell expr 30000 + $(KSU_GIT_VERSION)))
$(info -- KernelSU version: $(KSU_VERSION))
ccflags-y += -DKSU_VERSION=$(KSU_VERSION)

KSU_NEW_DCACHE_FLUSH := $(shell grep -q __flush_dcache_area $(srctree)/arch/arm64/include/asm/cacheflush.h ; echo $$?)
$(info -- KSU_NEW_DCACHE_FLUSH: $(KSU_NEW_DCACHE_FLUSH))


ifndef KSU_EXPECTED_SIZE
KSU_EXPECTED_SIZE := 0x375
endif

ifndef KSU_EXPECTED_HASH
KSU_EXPECTED_HASH := 484fcba6e6c43b1fb09700633bf2fb4758f13cb0b2f4457b80d075084b26c588
endif

ifdef KSU_MANAGER_PACKAGE
ccflags-y += -DKSU_MANAGER_PACKAGE=\"$(KSU_MANAGER_PACKAGE)\"
$(info -- KernelSU Manager package name: $(KSU_MANAGER_PACKAGE))
endif

$(info -- KernelSU Manager signature size: $(KSU_EXPECTED_SIZE))
$(info -- KernelSU Manager signature hash: $(KSU_EXPECTED_HASH))

ccflags-y += -DEXPECTED_SIZE=$(KSU_EXPECTED_SIZE)
ccflags-y += -DEXPECTED_HASH=\"$(KSU_EXPECTED_HASH)\"

ifdef KSU_EXPECTED_SIZE2
ifndef KSU_EXPECTED_HASH2
$(error KSU_EXPECTED_HASH2 must be set when KSU_EXPECTED_SIZE2 is set)
endif
ccflags-y += -DEXPECTED_SIZE2=$(KSU_EXPECTED_SIZE2)
ccflags-y += -DEXPECTED_HASH2=\"$(KSU_EXPECTED_HASH2)\"
$(info -- KernelSU Manager signature size2: $(KSU_EXPECTED_SIZE2))
$(info -- KernelSU Manager signature hash2: $(KSU_EXPECTED_HASH2))
endif

ccflags-y += -DKSU_NEW_DCACHE_FLUSH=$(KSU_NEW_DCACHE_FLUSH)

ccflags-y += -Wno-strict-prototypes -Wno-int-conversion -Wno-gcc-compat -Wno-missing-prototypes
ccflags-y += -Wno-declaration-after-statement -Wno-unused-function -Wno-unused-variable

# Keep a new line here!! Because someone may append config
